version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch

    steps:
      - checkout

      - restore_cache:
          key: venv-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            pip3 install pipenv
            pipenv install

      - run:
          name: build
          command: |
            pipenv run python3 app.py